### ISSUE TITLE
NullPointerException with publisher flag

### ISSUE THREAD

**Issue by ziegm** [ehealthsuisse/ch-epr-mhealth#15]
Error (NullPointerException) occurs with the publisher flag (local and ci build works), see steps below.

Run the new version of the ig publisher on a fresh clone with the publisher flag:
```
wget https://github.com/HL7/fhir-ig-publisher/releases/latest/download/publisher.jar -O publisher.jar
java -Xms3550m -Xmx3550m -jar publisher.jar -ig ig.ini -publish
```
```
java.lang.NullPointerException
        at org.hl7.fhir.igtools.publisher.Publisher.generateDataFile(Publisher.java:6262)
        at org.hl7.fhir.igtools.publisher.Publisher.generateSummaryOutputs(Publisher.java:5645)
        at org.hl7.fhir.igtools.publisher.Publisher.generate(Publisher.java:4905)
        at org.hl7.fhir.igtools.publisher.Publisher.createIg(Publisher.java:885)
        at org.hl7.fhir.igtools.publisher.Publisher.execute(Publisher.java:729)
        at org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:8414)
```

**Comment by oliveregger** [comment]
das publish flag braucht noch ein Argument (heisst targetUrl), soweit ich sehe wird es aber dann eigentlich gar nicht gebraucht, e.g: -publish file:///Users/oliveregger/Documents/github/ch-epr-mhealth/output

**Comment by ziegm** [comment]
works, thx
